name: Build Docker Image, Push to DockerHub and Deploy to VPS server

on: 
    push:
        branches: 
            - main

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Docker Metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ secrets.DOCKER_REPO }}

          - name: Build and Push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}

          - name: Deploy to VPS
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.KEY }}
              port: ${{ secrets.PORT }}
              passphrase: ${{ secrets.PASSPHRASE }}
              script: |
                cd ${{ secrets.LOCATION }}
                docker compose pull && docker compose up -d
